const state = { mode: 'study', stream: null, recorder: null, chunks: [], timer: null, busy: false };
const $ = (id) => document.getElementById(id);
const setMetric = (label, value) => `<div class="metric"><b>${value ?? 'UNKNOWN'}</b><span>${label}</span></div>`;
const toBase64 = (blob) => new Promise((resolve) => { const reader = new FileReader(); reader.onloadend = () => resolve(reader.result.split(',')[1]); reader.readAsDataURL(blob); });

function setWorker(id, status, model) { $(id + '-status').textContent = status; if (model) $(id + '-model').textContent = model; }
function captureFrame() { const video = $('camera'); if (!video.videoWidth) return null; const canvas = document.createElement('canvas'); canvas.width = video.videoWidth; canvas.height = video.videoHeight; canvas.getContext('2d').drawImage(video, 0, 0); return canvas.toDataURL('image/jpeg', .75).split(',')[1]; }
function showEntities(visual) { $('detections').textContent = visual.entities.length ? visual.entities.map((entity) => `${entity.label} ${(entity.confidence * 100).toFixed(1)}%`).join(' · ') : 'No detections returned.'; }
async function callWorker(path, payload) { const response = await fetch(path, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ ...payload, mode: state.mode }) }); const result = await response.json(); if (!response.ok) throw new Error(result.error || `${path} failed`); return result; }
async function analyze(audioBlob = null) {
  if (state.busy) return; state.busy = true; const frame = captureFrame(); setWorker('vision', frame ? 'RUNNING' : 'NO INPUT'); setWorker('speech', audioBlob ? 'RUNNING' : 'NO INPUT');
  try {
    const speechPayload = audioBlob ? { audio_b64: await toBase64(audioBlob), audio_mime_type: audioBlob.type } : {}; const visionPayload = frame ? { frame_b64: frame } : {}; const started = performance.now();
    const [visionResult, speechResult] = await Promise.all([callWorker('/api/vision', visionPayload), callWorker('/api/speech', speechPayload)]); const elapsed = performance.now() - started;
    const visual = visionResult.visual; const speech = speechResult.speech; setWorker('vision', visual.status, visual.model); const speechDetails = [speech.model, speech.audio_codec, speech.audio_sample_rate ? `${speech.audio_sample_rate}Hz` : null, speech.audio_duration_ms ? `${(speech.audio_duration_ms / 1000).toFixed(1)}s` : null].filter(Boolean).join(' · '); setWorker('speech', speech.status, speechDetails || speech.model); showEntities(visual); $('transcript').textContent = speech.transcript || (speech.status === 'UNKNOWN' ? 'Whisper-Tiny unavailable.' : speech.status === 'NO_SPEECH' ? 'No speech recognized in decoded audio.' : 'Speech decode failed.');
    const fused = await callWorker('/api/fuse', { speech, visual }); $('guidance').textContent = fused.decision.message; $('rationale').textContent = fused.decision.rationale.join(' · ') || 'No active signals.'; const t = fused.telemetry;
    $('metrics').innerHTML = [setMetric('end to end ms', elapsed.toFixed(2)), setMetric('vision ms', visionResult.telemetry.inference_ms?.toFixed(2)), setMetric('speech ms', speechResult.telemetry.inference_ms?.toFixed(2)), setMetric('fusion ms', t.fusion_ms?.toFixed(2)), setMetric('decision ms', t.decision_ms?.toFixed(2)), setMetric('memory', t.memory)].join(''); $('runtime-state').textContent = 'RUNNING';
  } catch (error) { $('runtime-state').textContent = 'FAILED'; $('guidance').textContent = error.message; } finally { state.busy = false; }
}
function scheduleAudioCycle() { if (!state.recorder || state.recorder.state !== 'inactive') return; state.chunks = []; state.recorder.start(); state.timer = setTimeout(() => state.recorder.stop(), 4000); }
$('connect').addEventListener('click', async () => { try { state.stream = await navigator.mediaDevices.getUserMedia({ video: true, audio: true }); $('camera').srcObject = state.stream; $('camera').style.display = 'block'; $('camera-placeholder').style.display = 'none'; $('camera-state').textContent = 'LIVE'; $('mic-state').textContent = 'LIVE'; $('connect').textContent = 'Sensors enabled'; const audioStream = new MediaStream(state.stream.getAudioTracks()); const mimeTypes = ['audio/webm;codecs=opus', 'audio/webm']; const mimeType = mimeTypes.find((candidate) => MediaRecorder.isTypeSupported(candidate)); if (!mimeType) throw new Error('No browser-supported WebM/Opus audio recorder'); state.recorder = new MediaRecorder(audioStream, { mimeType }); $('speech-model').textContent = `${state.recorder.mimeType} · waiting`; state.recorder.ondataavailable = (event) => { if (event.data.size) state.chunks.push(event.data); }; state.recorder.onstop = async () => { const chunks = state.chunks.splice(0); const audio = new Blob(chunks, { type: state.recorder.mimeType }); if (!audio.size) { $('transcript').textContent = 'Recorder returned an empty audio blob.'; setWorker('speech', 'FAILED', state.recorder.mimeType); } else { await analyze(audio); } scheduleAudioCycle(); }; scheduleAudioCycle(); } catch (error) { $('runtime-state').textContent = 'FAILED'; $('transcript').textContent = `Sensor setup failed: ${error.message}`; setWorker('vision', 'UNAVAILABLE'); setWorker('speech', 'UNAVAILABLE'); } });
document.querySelectorAll('.mode').forEach((button) => button.addEventListener('click', () => { document.querySelector('.mode.active').classList.remove('active'); button.classList.add('active'); state.mode = button.dataset.mode; analyze(); })); analyze();